/* Replace with your SQL commands */



CREATE TABLE users (
    ID SERIAL PRIMARY KEY,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE INT NOT NULL,
    PHONE VARCHAR(20) NOT NULL,
    LOCATION_TAG VARCHAR(255),
    ADDRESS VARCHAR(255),
    NID VARCHAR(19) NOT NULL,
    EXPERTISE VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    IMAGE_PATH VARCHAR(255)
);

CREATE TABLE chat (
    CHAT_ID SERIAL PRIMARY KEY,
    SENDER_ID INT NOT NULL,
    RECEIVER_ID INT NOT NULL,
    THREAD_ID INT NOT NULL,
    MESSAGE VARCHAR(255) NOT NULL
);
